### ISSUE TITLE
Problème avec le datepicker de versement

### ISSUE THREAD

**Issue by ZacBagids** [HumanAppEfrei/caramel#125]
https://github.com/HumanAppEfrei/caramel/blob/date-picker/application/views/don/create.php

Le datepicker ne fonctionne pas sur cette view. On a pourtant bien mis la classe 'datepicker' créée dans le footer...
Lorsque j'ai inspecté le code sur le navigateur j'ai eu une erreur de chargement du fichier suivant : jquery.flot.pie.min.js

**Comment by statox** [comment]
Réglé par Victor pendant le merge de date picker vers develop.
